### ISSUE TITLE
Prolong the domain or change it

### ISSUE THREAD

**Issue by AlexWayfer** [pry/pry.github.io#26]
Now the link from description and README returns 404…

https://pry.github.com/

![image](https://user-images.githubusercontent.com/6510020/181264325-7df81e6a-8fec-48d0-912b-52e0cf0d41e6.png)

Suggested https://pry.github.io/ BTW works.

**Comment by andrehjr** [comment]
Thanks for issue!

Updated repo to match github.io now. Since github.com no longer works.
